CREATE DATABASE PROJETOS;

CREATE TABLE FUNCIONARIO(
FMATRICULA CHAR (6) NOT NULL PRIMARY KEY,
FNOME VARCHAR (24) NOT NULL);

CREATE TABLE DEPARTAMENTO(
DCODIGO CHAR (6) NOT NULL PRIMARY KEY,
FNOME VARCHAR (24) NOT NULL);

CREATE TABLE PROJETOS(
PCODIGO CHAR (6) NOT NULL PRIMARY KEY,projetos
PNOME VARCHAR (24) NOT NULL,
DCODIGO CHAR (3) NOT NULL,
RESP CHAR (6) NOT NULL,
FOREIGN KEY (RESP) REFERENCES FUNCIONARIO (FMATRICULA),
DATAINI DATE,
DATAFIM DATE,
PSUPER CHAR (6),
FOREIGN KEY (PSUPER) REFERENCES PROJETOS (PCODIGO));testeteste
